2023-09-28 22:34:48,259 : INFO : Line No. : 62 - Start of script execution
2023-09-28 22:34:48,261 : INFO : Line No. : 73 - Storage for processed data: /Users/swmoeller/python/2023/large_language_model/BrainGPT/data/25_processed
2023-09-28 22:34:48,261 : INFO : Line No. : 76 - Log file on imported documents: /Users/swmoeller/python/2023/large_language_model/BrainGPT/logs/file_import_log.csv
2023-09-28 22:34:48,261 : INFO : Line No. : 79 - Source directory for documents: /Users/swmoeller/python/2023/large_language_model/BrainGPT/data/10_raw/doc2scan
2023-09-28 22:34:48,263 : ERROR : Line No. : 155 - Import tracking file </Users/swmoeller/python/2023/large_language_model/BrainGPT/logs/file_import_log.csv> is missing. Creating a new panda dataframe.
2023-09-28 22:34:48,267 : INFO : Line No. : 272 - Pandas Dataframe updated with files 'to be imported' or 'duplicated'.
2023-09-28 22:34:48,267 : INFO : Line No. : 288 - Possible file.extensions for document loader analyzed and list of extensions generated.
2023-09-28 22:34:48,267 : INFO : Line No. : 330 - Document state_of_the_union.txt loaded.
2023-09-28 22:34:48,268 : INFO : Line No. : 332 - Splitting of document <state_of_the_union.txt> done with <0> chunks. So far in total 42 chunks.
2023-09-28 22:34:48,608 : INFO : Line No. : 330 - Document Regulierung_von_Large_Language_Models_in_DSA_und_AIA-E_-_beck-online.pdf loaded.
2023-09-28 22:34:48,608 : INFO : Line No. : 332 - Splitting of document <Regulierung_von_Large_Language_Models_in_DSA_und_AIA-E_-_beck-online.pdf> done with <0> chunks. So far in total 64 chunks.
2023-09-28 22:34:48,609 : ERROR : Line No. : 377 - No vectorstore exists. New store established in </Users/swmoeller/python/2023/large_language_model/BrainGPT/data/25_processed>.
2023-09-28 22:34:48,619 : WARNING : Line No. : 25 - Unable to connect optimized C data functions [No module named 'clickhouse_connect.driverc.buffer'], falling back to pure Python
2023-09-28 22:34:48,619 : WARNING : Line No. : 33 - Unable to connect ClickHouse Connect C to Numpy API [No module named 'clickhouse_connect.driverc.npconv'], falling back to pure Python
2023-09-28 22:34:48,701 : INFO : Line No. : 45 - Using python library for writing JSON byte strings
2023-09-28 22:34:48,796 : INFO : Line No. : 464 - No existing DB found in /Users/swmoeller/python/2023/large_language_model/BrainGPT/data/25_processed, skipping load
2023-09-28 22:34:48,796 : INFO : Line No. : 476 - No existing DB found in /Users/swmoeller/python/2023/large_language_model/BrainGPT/data/25_processed, skipping load
2023-09-28 22:34:49,141 : INFO : Line No. : 382 - In total, 0 file chunks were imported into the vectorstore.
2023-09-28 22:34:49,142 : INFO : Line No. : 424 - Persisting DB to disk, putting it in the save folder: /Users/swmoeller/python/2023/large_language_model/BrainGPT/data/25_processed
2023-09-28 22:34:49,146 : INFO : Line No. : 418 - Document import list saved.
2023-09-28 22:34:49,146 : INFO : Line No. : 428 - End of script execution


2023-09-28 22:34:49,147 : INFO : Line No. : 424 - Persisting DB to disk, putting it in the save folder: /Users/swmoeller/python/2023/large_language_model/BrainGPT/data/25_processed
2023-09-29 07:31:49,384 : INFO : Line No. : 62 - Start of script execution
2023-09-29 07:31:49,386 : INFO : Line No. : 73 - Storage for processed data: /Users/swmoeller/python/2023/large_language_model/BrainGPT/data/25_processed
2023-09-29 07:31:49,386 : INFO : Line No. : 76 - Log file on imported documents: /Users/swmoeller/python/2023/large_language_model/BrainGPT/logs/file_import_log.csv
2023-09-29 07:31:49,386 : INFO : Line No. : 79 - Source directory for documents: /Users/swmoeller/python/2023/large_language_model/BrainGPT/data/10_raw/doc2scan
2023-09-29 07:31:49,388 : INFO : Line No. : 151 - [INFO] Start opening import tracking file
2023-09-29 07:31:49,388 : INFO : Line No. : 153 - Tracking file </Users/swmoeller/python/2023/large_language_model/BrainGPT/logs/file_import_log.csv> loaded into panda dataframe.

2023-09-29 07:31:49,393 : INFO : Line No. : 208 - [INFO] Generating & Updating list of files for import
2023-09-29 07:31:49,393 : INFO : Line No. : 224 - List with 3 documents updated.

2023-09-29 07:31:49,401 : INFO : Line No. : 279 - Pandas Dataframe updated with files 'to be imported' or 'duplicated'.
2023-09-29 07:31:49,401 : INFO : Line No. : 295 - Possible file.extensions for document loader analyzed and list of extensions generated.
2023-09-29 07:31:55,912 : INFO : Line No. : 337 - Document Bosch_Washing_Machine.pdf loaded.
2023-09-29 07:31:55,914 : INFO : Line No. : 340 - Splitting of document <Bosch_Washing_Machine.pdf> done with <105> chunks. So far in total 105 chunks.
2023-09-29 07:31:55,915 : INFO : Line No. : 337 - Document state_of_the_union.txt loaded.
2023-09-29 07:31:55,916 : INFO : Line No. : 340 - Splitting of document <state_of_the_union.txt> done with <42> chunks. So far in total 147 chunks.
2023-09-29 07:31:56,223 : INFO : Line No. : 337 - Document Regulierung_von_Large_Language_Models_in_DSA_und_AIA-E_-_beck-online.pdf loaded.
2023-09-29 07:31:56,224 : INFO : Line No. : 340 - Splitting of document <Regulierung_von_Large_Language_Models_in_DSA_und_AIA-E_-_beck-online.pdf> done with <22> chunks. So far in total 169 chunks.
2023-09-29 07:31:56,224 : INFO : Line No. : 359 - 
2023-09-29 07:31:56,224 : ERROR : Line No. : 387 - No vectorstore exists. New store established in </Users/swmoeller/python/2023/large_language_model/BrainGPT/data/25_processed>.
2023-09-29 07:31:56,273 : WARNING : Line No. : 25 - Unable to connect optimized C data functions [No module named 'clickhouse_connect.driverc.buffer'], falling back to pure Python
2023-09-29 07:31:56,273 : WARNING : Line No. : 33 - Unable to connect ClickHouse Connect C to Numpy API [No module named 'clickhouse_connect.driverc.npconv'], falling back to pure Python
2023-09-29 07:31:56,505 : INFO : Line No. : 45 - Using python library for writing JSON byte strings
2023-09-29 07:31:56,715 : INFO : Line No. : 470 - loaded in 0 embeddings
2023-09-29 07:31:56,719 : INFO : Line No. : 482 - loaded in 1 collections
2023-09-29 07:31:56,722 : INFO : Line No. : 93 - collection with name langchain already exists, returning existing collection
2023-09-29 07:31:57,225 : INFO : Line No. : 67 - message='Request to OpenAI API' method=post path=https://api.openai.com/v1/embeddings
2023-09-29 07:31:58,491 : INFO : Line No. : 67 - message='OpenAI API response' path=https://api.openai.com/v1/embeddings processing_ms=132 request_id=d299a638a91628cef4a3fa9c0acf7da6 response_code=200
2023-09-29 07:31:58,604 : INFO : Line No. : 392 - In total, 22 file chunks were imported into the vectorstore.
2023-09-29 07:31:58,604 : INFO : Line No. : 424 - Persisting DB to disk, putting it in the save folder: /Users/swmoeller/python/2023/large_language_model/BrainGPT/data/25_processed
2023-09-29 07:31:58,614 : INFO : Line No. : 428 - Document import list saved.
2023-09-29 07:31:58,614 : INFO : Line No. : 438 - End of script execution


2023-09-29 07:31:58,616 : INFO : Line No. : 424 - Persisting DB to disk, putting it in the save folder: /Users/swmoeller/python/2023/large_language_model/BrainGPT/data/25_processed
2023-09-29 07:41:45,335 : INFO : Line No. : 62 - Start of script execution
2023-09-29 07:41:45,337 : INFO : Line No. : 73 - Storage for processed data: /Users/swmoeller/python/2023/large_language_model/BrainGPT/data/25_processed
2023-09-29 07:41:45,337 : INFO : Line No. : 76 - Log file on imported documents: /Users/swmoeller/python/2023/large_language_model/BrainGPT/logs/file_import_log.csv
2023-09-29 07:41:45,337 : INFO : Line No. : 79 - Source directory for documents: /Users/swmoeller/python/2023/large_language_model/BrainGPT/data/10_raw/doc2scan
2023-09-29 07:41:45,340 : INFO : Line No. : 151 - [INFO] Start opening import tracking file
2023-09-29 07:41:45,340 : INFO : Line No. : 153 - Tracking file </Users/swmoeller/python/2023/large_language_model/BrainGPT/logs/file_import_log.csv> loaded into panda dataframe.

2023-09-29 07:41:45,343 : INFO : Line No. : 208 - [INFO] Generating & Updating list of files for import
2023-09-29 07:41:45,343 : INFO : Line No. : 224 - List with 3 documents updated.

2023-09-29 07:41:45,351 : INFO : Line No. : 279 - Pandas Dataframe updated with files 'to be imported' or 'duplicated'.
2023-09-29 07:41:45,352 : INFO : Line No. : 295 - Possible file.extensions for document loader analyzed and list of extensions generated.
2023-09-29 07:41:45,352 : INFO : Line No. : 359 - 
2023-09-29 07:41:45,368 : WARNING : Line No. : 25 - Unable to connect optimized C data functions [No module named 'clickhouse_connect.driverc.buffer'], falling back to pure Python
2023-09-29 07:41:45,368 : WARNING : Line No. : 33 - Unable to connect ClickHouse Connect C to Numpy API [No module named 'clickhouse_connect.driverc.npconv'], falling back to pure Python
2023-09-29 07:41:45,471 : INFO : Line No. : 45 - Using python library for writing JSON byte strings
2023-09-29 07:41:45,593 : INFO : Line No. : 470 - loaded in 22 embeddings
2023-09-29 07:41:45,594 : INFO : Line No. : 482 - loaded in 1 collections
2023-09-29 07:41:45,596 : INFO : Line No. : 93 - collection with name langchain already exists, returning existing collection
2023-09-29 07:41:45,596 : INFO : Line No. : 379 - Vectorstore loaded from loction </Users/swmoeller/python/2023/large_language_model/BrainGPT/data/25_processed>
2023-09-29 07:41:45,978 : INFO : Line No. : 384 - In total, 0 file chunks were imported into the vectorstore.
2023-09-29 07:41:45,980 : INFO : Line No. : 429 - Document import list saved.
2023-09-29 07:41:45,980 : INFO : Line No. : 439 - End of script execution


2023-09-29 07:41:45,980 : INFO : Line No. : 424 - Persisting DB to disk, putting it in the save folder: /Users/swmoeller/python/2023/large_language_model/BrainGPT/data/25_processed
2023-09-29 07:44:13,778 : INFO : Line No. : 62 - Start of script execution
2023-09-29 07:44:13,780 : INFO : Line No. : 73 - Storage for processed data: /Users/swmoeller/python/2023/large_language_model/BrainGPT/data/25_processed
2023-09-29 07:44:13,780 : INFO : Line No. : 76 - Log file on imported documents: /Users/swmoeller/python/2023/large_language_model/BrainGPT/logs/file_import_log.csv
2023-09-29 07:44:13,780 : INFO : Line No. : 79 - Source directory for documents: /Users/swmoeller/python/2023/large_language_model/BrainGPT/data/10_raw/doc2scan
2023-09-29 07:44:13,782 : INFO : Line No. : 151 - [INFO] Start opening import tracking file
2023-09-29 07:44:13,782 : INFO : Line No. : 153 - Tracking file </Users/swmoeller/python/2023/large_language_model/BrainGPT/logs/file_import_log.csv> loaded into panda dataframe.

2023-09-29 07:44:13,783 : INFO : Line No. : 208 - [INFO] Generating & Updating list of files for import
2023-09-29 07:44:13,783 : INFO : Line No. : 224 - List with 3 documents updated.

2023-09-29 07:44:13,787 : INFO : Line No. : 279 - Pandas Dataframe updated with files 'to be imported' or 'duplicated'.
2023-09-29 07:44:13,787 : INFO : Line No. : 295 - Possible file.extensions for document loader analyzed and list of extensions generated.
2023-09-29 07:44:13,787 : INFO : Line No. : 359 - [INFO] Checking, if vectorstore exists.
2023-09-29 07:44:13,787 : INFO : Line No. : 366 - Vectorstore exists at /Users/swmoeller/python/2023/large_language_model/BrainGPT/data/25_processed.
2023-09-29 07:44:13,798 : WARNING : Line No. : 25 - Unable to connect optimized C data functions [No module named 'clickhouse_connect.driverc.buffer'], falling back to pure Python
2023-09-29 07:44:13,798 : WARNING : Line No. : 33 - Unable to connect ClickHouse Connect C to Numpy API [No module named 'clickhouse_connect.driverc.npconv'], falling back to pure Python
2023-09-29 07:44:13,881 : INFO : Line No. : 45 - Using python library for writing JSON byte strings
2023-09-29 07:44:13,987 : INFO : Line No. : 470 - loaded in 22 embeddings
2023-09-29 07:44:13,988 : INFO : Line No. : 482 - loaded in 1 collections
2023-09-29 07:44:13,989 : INFO : Line No. : 93 - collection with name langchain already exists, returning existing collection
2023-09-29 07:44:13,989 : INFO : Line No. : 380 - Vectorstore loaded from loction </Users/swmoeller/python/2023/large_language_model/BrainGPT/data/25_processed>
2023-09-29 07:44:14,349 : INFO : Line No. : 385 - In total, 0 file chunks were imported into the vectorstore.
2023-09-29 07:44:14,350 : INFO : Line No. : 430 - Document import list saved.
2023-09-29 07:44:14,351 : INFO : Line No. : 440 - End of script execution


2023-09-29 07:44:14,351 : INFO : Line No. : 424 - Persisting DB to disk, putting it in the save folder: /Users/swmoeller/python/2023/large_language_model/BrainGPT/data/25_processed
2023-09-29 07:45:55,028 : INFO : Line No. : 62 - Start of script execution
2023-09-29 07:45:55,031 : INFO : Line No. : 73 - Storage for processed data: /Users/swmoeller/python/2023/large_language_model/BrainGPT/data/25_processed
2023-09-29 07:45:55,031 : INFO : Line No. : 76 - Log file on imported documents: /Users/swmoeller/python/2023/large_language_model/BrainGPT/logs/file_import_log.csv
2023-09-29 07:45:55,031 : INFO : Line No. : 79 - Source directory for documents: /Users/swmoeller/python/2023/large_language_model/BrainGPT/data/10_raw/doc2scan
2023-09-29 07:45:55,034 : INFO : Line No. : 151 - [INFO] Start opening import tracking file
2023-09-29 07:45:55,034 : INFO : Line No. : 153 - Tracking file </Users/swmoeller/python/2023/large_language_model/BrainGPT/logs/file_import_log.csv> loaded into panda dataframe.

2023-09-29 07:45:55,037 : INFO : Line No. : 208 - [INFO] Generating & Updating list of files for import
2023-09-29 07:45:55,037 : INFO : Line No. : 224 - List with 3 documents updated.

2023-09-29 07:45:55,043 : INFO : Line No. : 279 - Pandas Dataframe updated with files 'to be imported' or 'duplicated'.
2023-09-29 07:45:55,043 : INFO : Line No. : 294 - [INFO] Generating & Updating list of available document loader.
2023-09-29 07:45:55,043 : INFO : Line No. : 296 - Possible file.extensions for document loader analyzed and list of extensions generated

2023-09-29 07:45:55,043 : INFO : Line No. : 360 - [INFO] Checking, if vectorstore exists.
2023-09-29 07:45:55,044 : INFO : Line No. : 367 - Vectorstore exists at /Users/swmoeller/python/2023/large_language_model/BrainGPT/data/25_processed.
2023-09-29 07:45:55,061 : WARNING : Line No. : 25 - Unable to connect optimized C data functions [No module named 'clickhouse_connect.driverc.buffer'], falling back to pure Python
2023-09-29 07:45:55,061 : WARNING : Line No. : 33 - Unable to connect ClickHouse Connect C to Numpy API [No module named 'clickhouse_connect.driverc.npconv'], falling back to pure Python
2023-09-29 07:45:55,160 : INFO : Line No. : 45 - Using python library for writing JSON byte strings
2023-09-29 07:45:55,256 : INFO : Line No. : 470 - loaded in 22 embeddings
2023-09-29 07:45:55,257 : INFO : Line No. : 482 - loaded in 1 collections
2023-09-29 07:45:55,258 : INFO : Line No. : 93 - collection with name langchain already exists, returning existing collection
2023-09-29 07:45:55,258 : INFO : Line No. : 381 - Vectorstore loaded from loction </Users/swmoeller/python/2023/large_language_model/BrainGPT/data/25_processed>
2023-09-29 07:45:55,534 : INFO : Line No. : 386 - In total, 0 file chunks were imported into the vectorstore.
2023-09-29 07:45:55,536 : INFO : Line No. : 431 - Document import list saved.
2023-09-29 07:45:55,536 : INFO : Line No. : 441 - End of script execution


2023-09-29 07:45:55,536 : INFO : Line No. : 424 - Persisting DB to disk, putting it in the save folder: /Users/swmoeller/python/2023/large_language_model/BrainGPT/data/25_processed
2023-09-29 07:46:59,413 : INFO : Line No. : 62 - Start of script execution
2023-09-29 07:46:59,415 : INFO : Line No. : 73 - Storage for processed data: /Users/swmoeller/python/2023/large_language_model/BrainGPT/data/25_processed
2023-09-29 07:46:59,415 : INFO : Line No. : 76 - Log file on imported documents: /Users/swmoeller/python/2023/large_language_model/BrainGPT/logs/file_import_log.csv
2023-09-29 07:46:59,415 : INFO : Line No. : 79 - Source directory for documents: /Users/swmoeller/python/2023/large_language_model/BrainGPT/data/10_raw/doc2scan

2023-09-29 07:46:59,417 : INFO : Line No. : 151 - [INFO] Start opening import tracking file
2023-09-29 07:46:59,417 : INFO : Line No. : 153 - Tracking file </Users/swmoeller/python/2023/large_language_model/BrainGPT/logs/file_import_log.csv> loaded into panda dataframe.

2023-09-29 07:46:59,419 : INFO : Line No. : 208 - [INFO] Generating & Updating list of files for import
2023-09-29 07:46:59,420 : INFO : Line No. : 224 - List with 3 documents updated.

2023-09-29 07:46:59,424 : INFO : Line No. : 279 - Pandas Dataframe updated with files 'to be imported' or 'duplicated'.
2023-09-29 07:46:59,425 : INFO : Line No. : 294 - [INFO] Generating & Updating list of available document loader.
2023-09-29 07:46:59,425 : INFO : Line No. : 296 - Possible file.extensions for document loader analyzed and list of extensions generated

2023-09-29 07:46:59,425 : INFO : Line No. : 360 - [INFO] Checking, if vectorstore exists.
2023-09-29 07:46:59,425 : INFO : Line No. : 367 - Vectorstore exists at /Users/swmoeller/python/2023/large_language_model/BrainGPT/data/25_processed.
2023-09-29 07:46:59,440 : WARNING : Line No. : 25 - Unable to connect optimized C data functions [No module named 'clickhouse_connect.driverc.buffer'], falling back to pure Python
2023-09-29 07:46:59,440 : WARNING : Line No. : 33 - Unable to connect ClickHouse Connect C to Numpy API [No module named 'clickhouse_connect.driverc.npconv'], falling back to pure Python
2023-09-29 07:46:59,541 : INFO : Line No. : 45 - Using python library for writing JSON byte strings
2023-09-29 07:46:59,644 : INFO : Line No. : 470 - loaded in 22 embeddings
2023-09-29 07:46:59,645 : INFO : Line No. : 482 - loaded in 1 collections
2023-09-29 07:46:59,646 : INFO : Line No. : 93 - collection with name langchain already exists, returning existing collection
2023-09-29 07:46:59,646 : INFO : Line No. : 381 - Vectorstore loaded from loction </Users/swmoeller/python/2023/large_language_model/BrainGPT/data/25_processed>
2023-09-29 07:46:59,947 : INFO : Line No. : 386 - In total, 0 file chunks were imported into the vectorstore.
2023-09-29 07:46:59,948 : INFO : Line No. : 431 - Document import list saved.
2023-09-29 07:46:59,949 : INFO : Line No. : 441 - End of script execution


2023-09-29 07:46:59,949 : INFO : Line No. : 424 - Persisting DB to disk, putting it in the save folder: /Users/swmoeller/python/2023/large_language_model/BrainGPT/data/25_processed
2023-09-29 07:48:10,746 : INFO : Line No. : 62 - Start of script execution
2023-09-29 07:48:10,751 : INFO : Line No. : 73 - Storage for processed data: /Users/swmoeller/python/2023/large_language_model/BrainGPT/data/25_processed
2023-09-29 07:48:10,751 : INFO : Line No. : 76 - Log file on imported documents: /Users/swmoeller/python/2023/large_language_model/BrainGPT/logs/file_import_log.csv
2023-09-29 07:48:10,751 : INFO : Line No. : 79 - Source directory for documents: /Users/swmoeller/python/2023/large_language_model/BrainGPT/data/10_raw/doc2scan

2023-09-29 07:48:10,755 : INFO : Line No. : 151 - [INFO] Start opening import tracking file
2023-09-29 07:48:10,755 : INFO : Line No. : 153 - Tracking file </Users/swmoeller/python/2023/large_language_model/BrainGPT/logs/file_import_log.csv> loaded into panda dataframe.

2023-09-29 07:48:10,757 : INFO : Line No. : 208 - [INFO] Generating & Updating list of files for import
2023-09-29 07:48:10,757 : INFO : Line No. : 224 - List with 3 documents updated.

2023-09-29 07:48:10,773 : INFO : Line No. : 279 - Pandas Dataframe updated with files 'to be imported' or 'duplicated'.
2023-09-29 07:48:10,773 : INFO : Line No. : 294 - [INFO] Generating & Updating list of available document loader.
2023-09-29 07:48:10,774 : INFO : Line No. : 296 - Possible file.extensions for document loader analyzed and list of extensions generated

2023-09-29 07:48:10,774 : INFO : Line No. : 360 - [INFO] Checking, if vectorstore exists.
2023-09-29 07:48:10,774 : INFO : Line No. : 367 - Vectorstore exists at /Users/swmoeller/python/2023/large_language_model/BrainGPT/data/25_processed.

2023-09-29 07:48:10,799 : WARNING : Line No. : 25 - Unable to connect optimized C data functions [No module named 'clickhouse_connect.driverc.buffer'], falling back to pure Python
2023-09-29 07:48:10,799 : WARNING : Line No. : 33 - Unable to connect ClickHouse Connect C to Numpy API [No module named 'clickhouse_connect.driverc.npconv'], falling back to pure Python
2023-09-29 07:48:10,915 : INFO : Line No. : 45 - Using python library for writing JSON byte strings
2023-09-29 07:48:11,015 : INFO : Line No. : 470 - loaded in 22 embeddings
2023-09-29 07:48:11,016 : INFO : Line No. : 482 - loaded in 1 collections
2023-09-29 07:48:11,017 : INFO : Line No. : 93 - collection with name langchain already exists, returning existing collection
2023-09-29 07:48:11,017 : INFO : Line No. : 381 - Vectorstore loaded from loction </Users/swmoeller/python/2023/large_language_model/BrainGPT/data/25_processed>
2023-09-29 07:48:11,304 : INFO : Line No. : 386 - In total, 0 file chunks were imported into the vectorstore.
2023-09-29 07:48:11,306 : INFO : Line No. : 431 - Document import list saved.
2023-09-29 07:48:11,306 : INFO : Line No. : 441 - End of script execution


2023-09-29 07:48:11,306 : INFO : Line No. : 424 - Persisting DB to disk, putting it in the save folder: /Users/swmoeller/python/2023/large_language_model/BrainGPT/data/25_processed
2023-09-29 07:49:42,430 : INFO : Line No. : 62 - Start of script execution
2023-09-29 07:49:42,431 : INFO : Line No. : 73 - Storage for processed data: /Users/swmoeller/python/2023/large_language_model/BrainGPT/data/25_processed
2023-09-29 07:49:42,431 : INFO : Line No. : 76 - Log file on imported documents: /Users/swmoeller/python/2023/large_language_model/BrainGPT/logs/file_import_log.csv
2023-09-29 07:49:42,431 : INFO : Line No. : 79 - Source directory for documents: /Users/swmoeller/python/2023/large_language_model/BrainGPT/data/10_raw/doc2scan

2023-09-29 07:49:42,433 : INFO : Line No. : 151 - [INFO] Start opening import tracking file
2023-09-29 07:49:42,433 : INFO : Line No. : 153 - Tracking file </Users/swmoeller/python/2023/large_language_model/BrainGPT/logs/file_import_log.csv> loaded into panda dataframe.

2023-09-29 07:49:42,435 : INFO : Line No. : 208 - [INFO] Generating & Updating list of files for import.
2023-09-29 07:49:42,435 : INFO : Line No. : 224 - List with 3 documents updated.

2023-09-29 07:49:42,440 : INFO : Line No. : 279 - Pandas Dataframe updated with files 'to be imported' or 'duplicated'.
2023-09-29 07:49:42,440 : INFO : Line No. : 294 - [INFO] Generating & Updating list of available document loader.
2023-09-29 07:49:42,440 : INFO : Line No. : 296 - Possible file.extensions for document loader analyzed and list of extensions generated

2023-09-29 07:49:42,440 : INFO : Line No. : 360 - [INFO] Checking, if vectorstore exists.
2023-09-29 07:49:42,441 : INFO : Line No. : 367 - Vectorstore exists at /Users/swmoeller/python/2023/large_language_model/BrainGPT/data/25_processed.

2023-09-29 07:49:42,451 : WARNING : Line No. : 25 - Unable to connect optimized C data functions [No module named 'clickhouse_connect.driverc.buffer'], falling back to pure Python
2023-09-29 07:49:42,451 : WARNING : Line No. : 33 - Unable to connect ClickHouse Connect C to Numpy API [No module named 'clickhouse_connect.driverc.npconv'], falling back to pure Python
2023-09-29 07:49:42,536 : INFO : Line No. : 45 - Using python library for writing JSON byte strings
2023-09-29 07:49:42,615 : INFO : Line No. : 470 - loaded in 22 embeddings
2023-09-29 07:49:42,616 : INFO : Line No. : 482 - loaded in 1 collections
2023-09-29 07:49:42,617 : INFO : Line No. : 93 - collection with name langchain already exists, returning existing collection
2023-09-29 07:49:42,617 : INFO : Line No. : 381 - Vectorstore loaded from loction </Users/swmoeller/python/2023/large_language_model/BrainGPT/data/25_processed>
2023-09-29 07:49:42,895 : INFO : Line No. : 386 - In total, 0 file chunks were imported into the vectorstore.
2023-09-29 07:49:42,897 : INFO : Line No. : 431 - Document import list saved.
2023-09-29 07:49:42,897 : INFO : Line No. : 441 - End of script execution


2023-09-29 07:49:42,897 : INFO : Line No. : 424 - Persisting DB to disk, putting it in the save folder: /Users/swmoeller/python/2023/large_language_model/BrainGPT/data/25_processed
2023-09-29 07:50:52,312 : INFO : Line No. : 62 - Start of script execution
2023-09-29 07:50:52,314 : INFO : Line No. : 73 - Storage for processed data: /Users/swmoeller/python/2023/large_language_model/BrainGPT/data/25_processed
2023-09-29 07:50:52,314 : INFO : Line No. : 76 - Log file on imported documents: /Users/swmoeller/python/2023/large_language_model/BrainGPT/logs/file_import_log.csv
2023-09-29 07:50:52,314 : INFO : Line No. : 79 - Source directory for documents: /Users/swmoeller/python/2023/large_language_model/BrainGPT/data/10_raw/doc2scan

2023-09-29 07:50:52,316 : INFO : Line No. : 151 - [INFO] Start opening import tracking file
2023-09-29 07:50:52,316 : INFO : Line No. : 153 - Tracking file </Users/swmoeller/python/2023/large_language_model/BrainGPT/logs/file_import_log.csv> loaded into panda dataframe.

2023-09-29 07:50:52,318 : INFO : Line No. : 208 - [INFO] Generating & Updating list of files for import.
2023-09-29 07:50:52,318 : INFO : Line No. : 224 - List with 3 documents updated.

2023-09-29 07:50:52,323 : INFO : Line No. : 279 - Pandas Dataframe updated with 0 files, status set to 'to be imported' or 'duplicated'.

2023-09-29 07:50:52,323 : INFO : Line No. : 294 - [INFO] Generating & Updating list of available document loader.
2023-09-29 07:50:52,323 : INFO : Line No. : 296 - Possible file.extensions for document loader analyzed and list of extensions generated

2023-09-29 07:50:52,324 : INFO : Line No. : 360 - [INFO] Checking, if vectorstore exists.
2023-09-29 07:50:52,324 : INFO : Line No. : 367 - Vectorstore exists at /Users/swmoeller/python/2023/large_language_model/BrainGPT/data/25_processed.

2023-09-29 07:50:52,337 : WARNING : Line No. : 25 - Unable to connect optimized C data functions [No module named 'clickhouse_connect.driverc.buffer'], falling back to pure Python
2023-09-29 07:50:52,337 : WARNING : Line No. : 33 - Unable to connect ClickHouse Connect C to Numpy API [No module named 'clickhouse_connect.driverc.npconv'], falling back to pure Python
2023-09-29 07:50:52,421 : INFO : Line No. : 45 - Using python library for writing JSON byte strings
2023-09-29 07:50:52,500 : INFO : Line No. : 470 - loaded in 22 embeddings
2023-09-29 07:50:52,501 : INFO : Line No. : 482 - loaded in 1 collections
2023-09-29 07:50:52,502 : INFO : Line No. : 93 - collection with name langchain already exists, returning existing collection
2023-09-29 07:50:52,502 : INFO : Line No. : 381 - Vectorstore loaded from loction </Users/swmoeller/python/2023/large_language_model/BrainGPT/data/25_processed>
2023-09-29 07:50:52,771 : INFO : Line No. : 386 - In total, 0 file chunks were imported into the vectorstore.
2023-09-29 07:50:52,772 : INFO : Line No. : 431 - Document import list saved.
2023-09-29 07:50:52,772 : INFO : Line No. : 441 - End of script execution


2023-09-29 07:50:52,773 : INFO : Line No. : 424 - Persisting DB to disk, putting it in the save folder: /Users/swmoeller/python/2023/large_language_model/BrainGPT/data/25_processed
2023-09-29 07:56:33,139 : INFO : Line No. : 62 - Start of script execution
2023-09-29 07:56:33,141 : INFO : Line No. : 73 - Storage for processed data: /Users/swmoeller/python/2023/large_language_model/BrainGPT/data/25_processed
2023-09-29 07:56:33,142 : INFO : Line No. : 76 - Log file on imported documents: /Users/swmoeller/python/2023/large_language_model/BrainGPT/logs/file_import_log.csv
2023-09-29 07:56:33,142 : INFO : Line No. : 79 - Source directory for documents: /Users/swmoeller/python/2023/large_language_model/BrainGPT/data/10_raw/doc2scan

2023-09-29 07:56:33,144 : INFO : Line No. : 151 - [INFO] Start opening import tracking file
2023-09-29 07:56:33,145 : INFO : Line No. : 153 - Tracking file </Users/swmoeller/python/2023/large_language_model/BrainGPT/logs/file_import_log.csv> loaded into panda dataframe.

2023-09-29 07:56:33,147 : INFO : Line No. : 208 - [INFO] Generate panda dataframe out of files existing in import directory.
2023-09-29 07:56:33,147 : INFO : Line No. : 224 - 3 documents found in import directory. Next: Checking on import-status.

2023-09-29 07:56:33,148 : INFO : Line No. : 263 - [INFO] Validating import status of found files in import directory.
2023-09-29 07:56:33,153 : INFO : Line No. : 279 - Pandas Dataframe updated with 0 files, status set to 'to be imported' or 'duplicated'.

2023-09-29 07:56:33,153 : INFO : Line No. : 294 - [INFO] Generating & Updating list of available document loader.
2023-09-29 07:56:33,153 : INFO : Line No. : 296 - Possible file.extensions for document loader analyzed and list of extensions generated

2023-09-29 07:56:33,154 : INFO : Line No. : 360 - [INFO] Checking, if vectorstore exists.
2023-09-29 07:56:33,154 : INFO : Line No. : 367 - Vectorstore exists at /Users/swmoeller/python/2023/large_language_model/BrainGPT/data/25_processed.

2023-09-29 07:56:33,170 : WARNING : Line No. : 25 - Unable to connect optimized C data functions [No module named 'clickhouse_connect.driverc.buffer'], falling back to pure Python
2023-09-29 07:56:33,170 : WARNING : Line No. : 33 - Unable to connect ClickHouse Connect C to Numpy API [No module named 'clickhouse_connect.driverc.npconv'], falling back to pure Python
2023-09-29 07:56:33,280 : INFO : Line No. : 45 - Using python library for writing JSON byte strings
2023-09-29 07:56:33,393 : INFO : Line No. : 470 - loaded in 22 embeddings
2023-09-29 07:56:33,394 : INFO : Line No. : 482 - loaded in 1 collections
2023-09-29 07:56:33,395 : INFO : Line No. : 93 - collection with name langchain already exists, returning existing collection
2023-09-29 07:56:33,396 : INFO : Line No. : 381 - Vectorstore loaded from loction </Users/swmoeller/python/2023/large_language_model/BrainGPT/data/25_processed>
2023-09-29 07:56:33,719 : INFO : Line No. : 386 - In total, 0 file chunks were imported into the vectorstore.
2023-09-29 07:56:33,721 : INFO : Line No. : 431 - Document import list saved.
2023-09-29 07:56:33,721 : INFO : Line No. : 441 - End of script execution


2023-09-29 07:56:33,721 : INFO : Line No. : 424 - Persisting DB to disk, putting it in the save folder: /Users/swmoeller/python/2023/large_language_model/BrainGPT/data/25_processed
2023-09-29 08:01:49,859 : INFO : Line No. : 63 - Start of script execution
2023-09-29 08:01:49,861 : INFO : Line No. : 74 - Storage for processed data: /Users/swmoeller/python/2023/large_language_model/BrainGPT/data/25_processed
2023-09-29 08:01:49,861 : INFO : Line No. : 77 - Log file on imported documents: /Users/swmoeller/python/2023/large_language_model/BrainGPT/logs/file_import_log.csv
2023-09-29 08:01:49,861 : INFO : Line No. : 80 - Source directory for documents: /Users/swmoeller/python/2023/large_language_model/BrainGPT/data/10_raw/doc2scan

2023-09-29 08:01:49,863 : INFO : Line No. : 152 - [INFO] Start opening import tracking file
2023-09-29 08:01:49,863 : INFO : Line No. : 154 - Tracking file </Users/swmoeller/python/2023/large_language_model/BrainGPT/logs/file_import_log.csv> loaded into panda dataframe.

2023-09-29 08:01:49,865 : INFO : Line No. : 209 - [INFO] Generate panda dataframe out of files existing in import directory.
2023-09-29 08:01:49,866 : INFO : Line No. : 225 - 3 documents found in import directory. Next: Checking on import-status.

2023-09-29 08:01:49,866 : INFO : Line No. : 264 - [INFO] Validating import status of found files in import directory.
2023-09-29 08:01:49,872 : INFO : Line No. : 280 - Pandas Dataframe updated with 0 files, status set to 'to be imported' or 'duplicated'.

2023-09-29 08:01:49,872 : INFO : Line No. : 295 - [INFO] Generating & Updating list of available document loader.
2023-09-29 08:01:49,872 : INFO : Line No. : 297 - Possible file.extensions for document loader analyzed and list of extensions generated

2023-09-29 08:01:49,872 : INFO : Line No. : 361 - [INFO] Checking, if vectorstore exists.
2023-09-29 08:01:49,872 : INFO : Line No. : 368 - Vectorstore exists at /Users/swmoeller/python/2023/large_language_model/BrainGPT/data/25_processed.

2023-09-29 08:01:49,896 : WARNING : Line No. : 25 - Unable to connect optimized C data functions [No module named 'clickhouse_connect.driverc.buffer'], falling back to pure Python
2023-09-29 08:01:49,896 : WARNING : Line No. : 33 - Unable to connect ClickHouse Connect C to Numpy API [No module named 'clickhouse_connect.driverc.npconv'], falling back to pure Python
2023-09-29 08:01:50,067 : INFO : Line No. : 45 - Using python library for writing JSON byte strings
2023-09-29 08:01:50,149 : INFO : Line No. : 470 - loaded in 22 embeddings
2023-09-29 08:01:50,150 : INFO : Line No. : 482 - loaded in 1 collections
2023-09-29 08:01:50,151 : INFO : Line No. : 93 - collection with name langchain already exists, returning existing collection
2023-09-29 08:01:50,151 : INFO : Line No. : 382 - Vectorstore loaded from loction </Users/swmoeller/python/2023/large_language_model/BrainGPT/data/25_processed>
2023-09-29 08:01:50,439 : INFO : Line No. : 387 - In total, 0 file chunks were imported into the vectorstore.
2023-09-29 08:01:50,441 : INFO : Line No. : 432 - Document import list saved.
2023-09-29 08:01:50,943 : INFO : Line No. : 443 - End of script execution


2023-09-29 08:01:50,944 : INFO : Line No. : 424 - Persisting DB to disk, putting it in the save folder: /Users/swmoeller/python/2023/large_language_model/BrainGPT/data/25_processed
2023-09-29 08:03:22,609 : INFO : Line No. : 63 - Start of script execution
2023-09-29 08:03:22,611 : INFO : Line No. : 74 - Storage for processed data: /Users/swmoeller/python/2023/large_language_model/BrainGPT/data/25_processed
2023-09-29 08:03:22,611 : INFO : Line No. : 77 - Log file on imported documents: /Users/swmoeller/python/2023/large_language_model/BrainGPT/logs/file_import_log.csv
2023-09-29 08:03:22,611 : INFO : Line No. : 80 - Source directory for documents: /Users/swmoeller/python/2023/large_language_model/BrainGPT/data/10_raw/doc2scan

2023-09-29 08:03:22,614 : INFO : Line No. : 152 - [INFO] Start opening import tracking file
2023-09-29 08:03:22,614 : INFO : Line No. : 154 - Tracking file </Users/swmoeller/python/2023/large_language_model/BrainGPT/logs/file_import_log.csv> loaded into panda dataframe.

2023-09-29 08:03:22,616 : INFO : Line No. : 209 - [INFO] Generate panda dataframe out of files existing in import directory.
2023-09-29 08:03:22,616 : INFO : Line No. : 225 - 3 documents found in import directory. Next: Checking on import-status.

2023-09-29 08:03:22,617 : INFO : Line No. : 264 - [INFO] Validating import status of found files in import directory.
2023-09-29 08:03:22,622 : INFO : Line No. : 280 - Pandas Dataframe updated with 0 files, status set to 'to be imported' or 'duplicated'.

2023-09-29 08:03:22,622 : INFO : Line No. : 295 - [INFO] Generating & Updating list of available document loader.
2023-09-29 08:03:22,622 : INFO : Line No. : 297 - Possible file.extensions for document loader analyzed and list of extensions generated

2023-09-29 08:03:22,623 : INFO : Line No. : 361 - [INFO] Checking, if vectorstore exists.
2023-09-29 08:03:22,623 : INFO : Line No. : 368 - Vectorstore exists at /Users/swmoeller/python/2023/large_language_model/BrainGPT/data/25_processed.

2023-09-29 08:03:22,638 : WARNING : Line No. : 25 - Unable to connect optimized C data functions [No module named 'clickhouse_connect.driverc.buffer'], falling back to pure Python
2023-09-29 08:03:22,638 : WARNING : Line No. : 33 - Unable to connect ClickHouse Connect C to Numpy API [No module named 'clickhouse_connect.driverc.npconv'], falling back to pure Python
2023-09-29 08:03:22,735 : INFO : Line No. : 45 - Using python library for writing JSON byte strings
2023-09-29 08:03:22,823 : INFO : Line No. : 470 - loaded in 22 embeddings
2023-09-29 08:03:22,824 : INFO : Line No. : 482 - loaded in 1 collections
2023-09-29 08:03:22,825 : INFO : Line No. : 93 - collection with name langchain already exists, returning existing collection
2023-09-29 08:03:22,825 : INFO : Line No. : 382 - Vectorstore loaded from loction </Users/swmoeller/python/2023/large_language_model/BrainGPT/data/25_processed>
2023-09-29 08:03:23,147 : INFO : Line No. : 387 - In total, 0 file chunks were imported into the vectorstore.
2023-09-29 08:03:24,151 : INFO : Line No. : 433 - Document import list saved.
2023-09-29 08:03:24,652 : INFO : Line No. : 444 - End of script execution


2023-09-29 08:03:24,652 : INFO : Line No. : 424 - Persisting DB to disk, putting it in the save folder: /Users/swmoeller/python/2023/large_language_model/BrainGPT/data/25_processed
2023-09-29 08:45:02,784 : INFO : Line No. : 63 - Start of script execution
2023-09-29 08:45:02,786 : INFO : Line No. : 74 - Storage for processed data: /Users/swmoeller/python/2023/large_language_model/BrainGPT/data/25_processed
2023-09-29 08:45:02,787 : INFO : Line No. : 77 - Log file on imported documents: /Users/swmoeller/python/2023/large_language_model/BrainGPT/logs/file_import_log.csv
2023-09-29 08:45:02,787 : INFO : Line No. : 80 - Source directory for documents: /Users/swmoeller/python/2023/large_language_model/BrainGPT/data/10_raw/doc2scan

2023-09-29 08:45:02,789 : INFO : Line No. : 152 - [INFO] Start opening import tracking file
2023-09-29 08:45:02,789 : INFO : Line No. : 154 - Tracking file </Users/swmoeller/python/2023/large_language_model/BrainGPT/logs/file_import_log.csv> loaded into panda dataframe.

2023-09-29 08:45:02,791 : INFO : Line No. : 209 - [INFO] Generate panda dataframe out of files existing in import directory.
2023-09-29 08:45:02,791 : INFO : Line No. : 225 - 3 documents found in import directory. Next: Checking on import-status.

2023-09-29 08:45:02,792 : INFO : Line No. : 264 - [INFO] Validating import status of found files in import directory.
2023-09-29 08:45:02,796 : INFO : Line No. : 280 - Pandas Dataframe updated with 0 files, status set to 'to be imported' or 'duplicated'.

2023-09-29 08:45:02,796 : INFO : Line No. : 295 - [INFO] Generating & Updating list of available document loader.
2023-09-29 08:45:02,796 : INFO : Line No. : 297 - Possible file.extensions for document loader analyzed and list of extensions generated

2023-09-29 08:45:02,797 : INFO : Line No. : 361 - [INFO] Checking, if vectorstore exists.
2023-09-29 08:45:02,797 : INFO : Line No. : 368 - Vectorstore exists at /Users/swmoeller/python/2023/large_language_model/BrainGPT/data/25_processed.

2023-09-29 08:45:02,809 : WARNING : Line No. : 25 - Unable to connect optimized C data functions [No module named 'clickhouse_connect.driverc.buffer'], falling back to pure Python
2023-09-29 08:45:02,810 : WARNING : Line No. : 33 - Unable to connect ClickHouse Connect C to Numpy API [No module named 'clickhouse_connect.driverc.npconv'], falling back to pure Python
2023-09-29 08:45:02,895 : INFO : Line No. : 45 - Using python library for writing JSON byte strings
2023-09-29 08:45:02,975 : INFO : Line No. : 470 - loaded in 22 embeddings
2023-09-29 08:45:02,976 : INFO : Line No. : 482 - loaded in 1 collections
2023-09-29 08:45:02,977 : INFO : Line No. : 93 - collection with name langchain already exists, returning existing collection
2023-09-29 08:45:02,977 : INFO : Line No. : 382 - Vectorstore loaded from loction </Users/swmoeller/python/2023/large_language_model/BrainGPT/data/25_processed>
2023-09-29 08:45:03,241 : INFO : Line No. : 387 - In total, 0 file chunks were imported into the vectorstore.
2023-09-29 08:45:04,248 : INFO : Line No. : 433 - Document import list saved.
2023-09-29 08:45:04,748 : INFO : Line No. : 444 - End of script execution


2023-09-29 08:45:04,749 : INFO : Line No. : 424 - Persisting DB to disk, putting it in the save folder: /Users/swmoeller/python/2023/large_language_model/BrainGPT/data/25_processed
2023-09-29 08:47:21,052 : INFO : Line No. : 63 - Start of script execution
2023-09-29 08:47:21,055 : INFO : Line No. : 74 - Storage for processed data: /Users/swmoeller/python/2023/large_language_model/BrainGPT/data/25_processed
2023-09-29 08:47:21,055 : INFO : Line No. : 77 - Log file on imported documents: /Users/swmoeller/python/2023/large_language_model/BrainGPT/logs/file_import_log.csv
2023-09-29 08:47:21,055 : INFO : Line No. : 80 - Source directory for documents: /Users/swmoeller/python/2023/large_language_model/BrainGPT/data/10_raw/doc2scan

2023-09-29 08:47:21,058 : INFO : Line No. : 152 - [INFO] Start opening import tracking file
2023-09-29 08:47:21,058 : INFO : Line No. : 154 - Tracking file </Users/swmoeller/python/2023/large_language_model/BrainGPT/logs/file_import_log.csv> loaded into panda dataframe.

2023-09-29 08:47:21,061 : INFO : Line No. : 209 - [INFO] Generate panda dataframe out of files existing in import directory.
2023-09-29 08:47:21,061 : INFO : Line No. : 225 - 3 documents found in import directory. Next: Checking on import-status.

2023-09-29 08:47:21,062 : INFO : Line No. : 264 - [INFO] Validating import status of found files in import directory.
2023-09-29 08:47:21,068 : INFO : Line No. : 280 - Pandas Dataframe updated with 0 files, status set to 'to be imported' or 'duplicated'.

2023-09-29 08:47:21,068 : INFO : Line No. : 295 - [INFO] Generating & Updating list of available document loader.
2023-09-29 08:47:21,068 : INFO : Line No. : 297 - Possible file.extensions for document loader analyzed and list of extensions generated

2023-09-29 08:47:21,068 : INFO : Line No. : 361 - [INFO] Checking, if vectorstore exists.
2023-09-29 08:47:21,069 : INFO : Line No. : 368 - Vectorstore exists at /Users/swmoeller/python/2023/large_language_model/BrainGPT/data/25_processed.

2023-09-29 08:47:21,086 : WARNING : Line No. : 25 - Unable to connect optimized C data functions [No module named 'clickhouse_connect.driverc.buffer'], falling back to pure Python
2023-09-29 08:47:21,086 : WARNING : Line No. : 33 - Unable to connect ClickHouse Connect C to Numpy API [No module named 'clickhouse_connect.driverc.npconv'], falling back to pure Python
2023-09-29 08:47:21,197 : INFO : Line No. : 45 - Using python library for writing JSON byte strings
2023-09-29 08:47:21,310 : INFO : Line No. : 470 - loaded in 22 embeddings
2023-09-29 08:47:21,311 : INFO : Line No. : 482 - loaded in 1 collections
2023-09-29 08:47:21,312 : INFO : Line No. : 93 - collection with name langchain already exists, returning existing collection
2023-09-29 08:47:21,313 : INFO : Line No. : 382 - Vectorstore loaded from loction </Users/swmoeller/python/2023/large_language_model/BrainGPT/data/25_processed>
2023-09-29 08:47:21,630 : INFO : Line No. : 387 - In total, 0 file chunks were imported into the vectorstore.

2023-09-29 08:47:21,631 : INFO : Line No. : 433 - Document import list saved.
2023-09-29 08:47:22,134 : INFO : Line No. : 444 - End of script execution


2023-09-29 08:47:22,134 : INFO : Line No. : 424 - Persisting DB to disk, putting it in the save folder: /Users/swmoeller/python/2023/large_language_model/BrainGPT/data/25_processed
